services:
  backend:
    build:
      context: ./docker/php
    restart: unless-stopped
    volumes:
      - ./src/backend:/var/www/html
      - ./docker/php/php.prod.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  frontend-build:
    image: node:18-alpine
    restart: no
    working_dir: /app
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
      - front-build-artifact:/app/dist
    command: sh -c "npm install && npm run build && exit 0"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://${SITE_DOMAIN}:${SITE_PORT}/api/v1

  proxy:
    image: nginx:alpine
    ports:
      - "5000:80"
    restart: unless-stopped
    volumes:
      - front-build-artifact:/var/www/html/frontend/
      - ./docker/nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend-build

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/my.prod.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  db-data:
  front-build-artifact: