services:
  # PHPサービス
  backend:
    build:
      context: ./docker/php
    volumes:
      - ./src/backend:/var/www/html
      - ./docker/php/php.dev.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000/api/v1

  # Nginxサービス
  proxy:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./src/backend:/var/www/html
      - ./docker/nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  # MySQLサービス
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/my.dev.cnf:/etc/mysql/conf.d/my.cnf

    

volumes:
  db-data: